version: '3.8'
networks:
  app-tier:
    driver: bridge
services:
  api:
    platform: linux/amd64
    container_name: API
    stdin_open: true
    tty: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
        - .:/app
    networks:
      - app-tier