name: Run Commit Extractor Script

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**/commits.csv'
      - '**/last_checked.json'
      - '**/last_shas.json'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Execute script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python extract.py

